Feature/deploy note
CAFECA-IO/BAIFA-web-crawling pull request #25
Opened 2024-01-04 06:15 UTC by gibbs-shih

### DEVELOP

### CHECK LIST
[Naming convention](https://github.com/CAFECA-IO/WorkGuidelines/blob/main/technology/coding-convention/naming-convention.md) verification: checked
Coding style verification: checked
new Library: 0
new Class / Component: 0
new loop: 1 
/src/crawler.ts (line26) setInterval 5000
high risk: 0
new sql: 0

### UML

2024-01-05 03:29 UTC, Luphia requested changes

2024-01-05 03:29 UTC, Luphia commented on .env.sample
>  //PostgreSQL
- follow [annotation format](https://github.com/CAFECA-IO/WorkGuidelines/blob/main/technology/annotation.md)

2024-01-05 03:29 UTC, Luphia commented on .env.sample
> +//network
- follow [annotation format](https://github.com/CAFECA-IO/WorkGuidelines/blob/main/technology/annotation.md)

2024-01-05 03:29 UTC, Luphia commented on src/crawler.ts
> +    // conduct every 5 seconds
- follow [annotation format](https://github.com/CAFECA-IO/WorkGuidelines/blob/main/technology/annotation.md)

2024-01-11 03:42 UTC, gibbs-shih commented on .env.sample
>  //PostgreSQL
done~

2024-01-11 03:42 UTC, gibbs-shih commented on .env.sample
> +//network
done~

2024-01-11 03:42 UTC, gibbs-shih commented on src/crawler.ts
> +    // conduct every 5 seconds
done~

2024-01-12 11:41 UTC, Luphia approved these changes

2024-01-12 11:42 UTC, Luphia approved these changes
- no bug found

2024-01-12 11:42 UTC, merged